trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'kk-service-connection'
  resourceGroupName: 'EventGridHybridConnectionRG'
  location: 'uk-south'
  templateFile: 'start/infra/main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- script: ls -la
  displayName: 'List files in the directory'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    #overrideParameters: '-location $(location)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'